#ifndef ENUMERATORS_H
#define ENUMERATORS_H

enum SEASONS { WINTER, SPRING, SUMMER, AUTUMN, SEASONS_COUNT };
enum DAYTYPE { WEEKDAY, WEEKEND, HOLIDAY, DAYTYPES_COUNT };
enum PERSONTYPE { ADULT, CHILD, BEN, PERSONTYPES_COUNT };
enum RANDOM_GENERATOR_TYPE { LINEAR, NORMAL };

#endif // ENUMERATORS_H
